runtime: php
env: flex

runtime_config:
  enable_stackdriver_integration: true
  operating_system: "ubuntu18"
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env
  - .git
  - .gitignore
  - .idea
  - .vscode

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

handlers:
  - url: /(.*\.(gif|png|jpg|css|js|svg|woff2|ttf))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js|svg|woff2|ttf)$
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  APP_DEBUG: true
  APP_ENV: production
  APP_KEY: base64:VSBsyo6yyY3tP3tnyq4cGg/lw/Ww3HMFtXJovXYfND0=
  APP_NAME: "GCP App - Lab 1 - CI/CD"
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp

  LOG_LEVEL: debug
